# This branch collects all parameters related to loading the trajectory and map data
dataset:
    name: hotel
    data: [/dataset/eth_data/biwi_hotel.ndjson]
    frequency: 2.5
    annotation interval: 10
    goals: /dataset/eth_data/destinations-hotel.txt
    map:
      type: pic # type: pic or sem(semantic)
      picture: /dataset/eth_data/map-hotel.png
      H_matrix: /dataset/eth_data/H-hotel.txt
      obstacle_type: 1 # What obstacles are considered: 0 for obstacle-unaware, 1 for grid-map, 2 for point-radius obstacles


# This branch collects all parameters related to the benchmark and experiment setup
benchmark:
  setup:
    interpolate: True
    smooth: 5 # 0 for no smoothing
    downsample: False
    downsample rate: 1 # fps (?) NULL for no downsampling
    downsample map: False
    downsample map rate: 3
    added_noise_sigma: 0 # 0 for no added noise

    observation period: 6
    prediction horizon: 10