# This branch collects all parameters related to loading the trajectory and map data
dataset:
    name: atc
    data: [/dataset/atc_data/atc-20121024_frame500000-traj.ndjson, /dataset/atc_data/atc-20121024_frame800000-traj.ndjson, /dataset/atc_data/atc-20121024_frame1500000-traj.ndjson]
    frequency: 25.9
    annotation interval: 1
    goals: NULL
    map: NULL
  #map: Please figure out an input format for the map!


# This branch collects all parameters related to the benchmark and experiment setup
benchmark:
  setup:
    interpolate: True
    smooth: 5 # 0 for no smoothing
    downsample: True
    downsample rate: 10 # fps (?) NULL for no downsampling
    downsample map: False
    downsample map rate: 3
    added_noise_sigma: 0.0 # 0 for no added noise

    observation period: 8
    prediction horizon: 12