class: Predictor_CVM
param:
  meta: 
    v0_mode: gaussian # gaussian / linear / constant
    v0_sigma: 1.5 # This is the sigma value to determine the v0 (i.e. velocity filtering)
    set_goal: True # Projecting the local nagigation goal in front of the agent
    goal_step: 20 # This is the amount of steps projected ahead of the agent to simulate the local goal
    load_goal: False
  uncertainty:
    uncertainty: False
    num_particles: 5
    uncertainty sigma: 0.3